/* Record real scripted UI actions in a fresh private store. No response fixtures or model grants. */
const {chromium}=require('playwright');
const fs=require('node:fs');const path=require('node:path');const {spawn}=require('node:child_process');const assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]);if(!process.argv[2]||fs.existsSync(root))throw Error('new output directory required');fs.mkdirSync(root,{recursive:true,mode:0o700});
const errors=[],shots=[];let child,browser,origin;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function open(){const c=await browser.newContext({viewport:{width:1280,height:650},recordVideo:{dir:root,size:{width:1280,height:650}},reducedMotion:'reduce'});await c.route('**/*',r=>r.request().url().startsWith(origin+'/')?r.continue():(errors.push('external request'),r.abort()));const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.locator('#case-list button').nth(8).waitFor();return {c,p};}
async function ready(p){await p.waitForFunction(()=>!document.querySelector('#packet-content').hidden,{timeout:20000});}
async function scroll(p,selector,offset=30){await p.locator(selector).evaluate((el,off)=>window.scrollTo({top:el.getBoundingClientRect().top+scrollY-off,behavior:'smooth'}),offset);await wait(650);}
async function shot(id,seconds,actions){const {c,p}=await open();const started=Date.now();await actions(p);await wait(Math.max(900,seconds*1000-(Date.now()-started)));await p.screenshot({path:path.join(root,id+'.png')});await c.close();const file=await p.video().path();fs.renameSync(file,path.join(root,id+'.webm'));shots.push({id,recording:id+'.webm',execution:'actual local UI recording; real Strands SDK with scripted provider',elapsed_ms:Date.now()-started});console.log(id+' captured',flush=true);}
(async()=>{try{
child=spawn(path.resolve('.venv/bin/python'),['-m','secops_triage.workspace','--root',path.join(root,'workspace'),'--port','0'],{stdio:['ignore','pipe','pipe']});
origin=await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(Error('startup timeout')),15000);child.stdout.on('data',d=>{const m=String(d).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(timer);res(m[0]);}});child.once('exit',()=>rej(Error('server exited')));});
browser=await chromium.launch({headless:true,channel:'chrome'});
await shot('02-start',14,async p=>{await wait(2800);await p.locator('#start').hover();await wait(1200);await p.locator('#start').click();await ready(p);assert.equal(await p.locator('#trace>li').count(),9);await wait(2500);});
await shot('03-trace',14,async p=>{await ready(p);await scroll(p,'.trace-section');await wait(4500);await p.locator('#trace .citation').first().click();await wait(3500);await p.locator('#close-source').click();});
await shot('04-messages',17,async p=>{await ready(p);await scroll(p,'#message-section');assert.equal(await p.locator('#messages>.message').count(),2);await wait(6000);await p.getByRole('button',{name:'Inspect scoped authorization',exact:true}).click();await wait(4500);await p.locator('#close-source').click();await scroll(p,'#message-section');});
await shot('05-evidence',16,async p=>{await ready(p);await scroll(p,'.recommendation');await wait(1800);const source=p.getByRole('button',{name:'View indicator: intelligence-exact-followup',exact:true});await source.scrollIntoViewIfNeeded();await source.click();await wait(6000);assert.match(await p.locator('#source-heading').innerText(),/intelligence-exact-followup/);await p.locator('#close-source').click();await scroll(p,'.unknowns');await wait(1800);});
await shot('06-handoff',14,async p=>{await ready(p);await scroll(p,'.decision-panel');await p.locator('#actor').fill('Demo operator (automated)');await p.locator('#reason').fill('Follow-up URL is flagged by synthetic intelligence; first-message training approval does not cover it.');await p.locator('#missing').fill('Credential submission and account compromise are unproven.');await p.locator('#next-action').fill('Request an authorized identity audit export and inspect the exact follow-up URL.');await p.locator('#save').scrollIntoViewIfNeeded();await wait(2500);await p.locator('#save').click();await p.locator('#copy-note').waitFor();await p.reload();await ready(p);await scroll(p,'.decision-panel');assert.match(await p.locator('#saved-records').innerText(),/Demo operator \(automated\)/);});
const {c,p}=await open();await ready(p);const runId=await p.locator('#history').inputValue();const view=await p.evaluate(async id=>await(await fetch('/api/runs/'+id)).json(),runId);assert.equal(view.sessions.length,1);assert.equal(view.evidence.length,9);assert.equal(view.handoffs.length,1);assert.equal(view.reviews.length,0);await c.close();
fs.writeFileSync(path.join(root,'recording-evidence.json'),JSON.stringify({source_commit:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),run_id:runId,packet_hash:view.packet.packet_hash,tools:[...new Set(view.trace.map(x=>x.tool))],evidence_reads:view.evidence.length,sessions:view.sessions,local_handoff_actor:view.handoffs[0].actor,human_acceptance:false,aws_actions:false,paid_investigation_calls:0,shots,errors},null,2),{mode:0o600});assert.deepEqual(errors,[]);
}catch(e){fs.writeFileSync(path.join(root,'capture-failure.txt'),e.stack,{mode:0o600});console.error('Capture failed; evidence preserved.');process.exitCode=1;}finally{if(browser)await browser.close();if(child&&child.exitCode===null){const ended=new Promise(r=>child.once('exit',r));child.kill('SIGINT');await ended;}}})();
